export const getCourseListRes = {
  code: '10000',
  message: 'Success',
  data: [
    {
      name: '大学英语（二）',
      teacher: '朱颖莉',
      scheduleRules: [
        {
          location: '铜盘B108',
          startClass: 1,
          endClass: 2,
          startWeek: 5,
          endWeek: 20,
          weekday: 2,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240100900009080',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=00900009',
      rawScheduleRules: '05-20 星期2:1-2节 铜盘B108\n',
      rawAdjust: '',
    },
    {
      name: '形势与政策（一）',
      teacher: '夏芬,王吉宇,林宇晖,蓝华生',
      scheduleRules: [
        {
          location: '铜盘A201',
          startClass: 1,
          endClass: 2,
          startWeek: 5,
          endWeek: 8,
          weekday: 6,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240102700013087',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=02700013',
      rawScheduleRules: '05-08 星期6:1-2节 铜盘A201\n',
      rawAdjust: '',
    },
    {
      name: '思想道德与法治',
      teacher: '刘翠林',
      scheduleRules: [
        {
          location: '铜盘B507',
          startClass: 5,
          endClass: 6,
          startWeek: 5,
          endWeek: 20,
          weekday: 2,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240102700029041',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=02700029',
      rawScheduleRules: '05-20 星期2:5-6节 铜盘B507\n',
      rawAdjust: '',
    },
    {
      name: '体育（一）',
      teacher: '吴杰忠',
      scheduleRules: [
        {
          location: '铜盘教学楼',
          startClass: 5,
          endClass: 6,
          startWeek: 5,
          endWeek: 20,
          weekday: 3,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240102800008084',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=02800008',
      rawScheduleRules: '05-20 星期3:5-6节 铜盘教学楼\n',
      rawAdjust: '',
    },
    {
      name: '大学生心理健康教育',
      teacher: '李艳华',
      scheduleRules: [
        {
          location: '铜盘B312',
          startClass: 7,
          endClass: 8,
          startWeek: 5,
          endWeek: 12,
          weekday: 1,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240102900792086',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=02900792',
      rawScheduleRules: '05-12 星期1:7-8节 铜盘B312\n',
      rawAdjust: '',
    },
    {
      name: '大学生国家安全教育',
      teacher: '',
      scheduleRules: [],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240106700004025',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=06700004',
      rawScheduleRules: '',
      rawAdjust: '',
    },
    {
      name: '大学生职业生涯规划',
      teacher: '邓建文',
      scheduleRules: [
        {
          location: '铜盘A109',
          startClass: 7,
          endClass: 8,
          startWeek: 7,
          endWeek: 10,
          weekday: 6,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240106800009050',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=06800009',
      rawScheduleRules: '07-10 星期6:7-8节 铜盘A109\n',
      rawAdjust: '',
    },
    {
      name: '线性代数',
      teacher: '王鹏',
      scheduleRules: [
        {
          location: '铜盘B207',
          startClass: 3,
          endClass: 4,
          startWeek: 9,
          endWeek: 16,
          weekday: 2,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '铜盘B207',
          startClass: 1,
          endClass: 2,
          startWeek: 9,
          endWeek: 16,
          weekday: 4,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240100300391045',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=00300391',
      rawScheduleRules:
        '09-16 星期2:3-4节 铜盘B207\n09-16 星期4:1-2节 铜盘B207\n',
      rawAdjust: '',
    },
    {
      name: '高等数学B（上）',
      teacher: '张梦晨',
      scheduleRules: [
        {
          location: '铜盘A110',
          startClass: 3,
          endClass: 4,
          startWeek: 5,
          endWeek: 18,
          weekday: 1,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '铜盘A110',
          startClass: 1,
          endClass: 2,
          startWeek: 5,
          endWeek: 17,
          weekday: 3,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '铜盘A110',
          startClass: 3,
          endClass: 4,
          startWeek: 5,
          endWeek: 17,
          weekday: 5,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240100310526035',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=00310526',
      rawScheduleRules:
        '05-18 星期1:3-4节 铜盘A110\n05-17 星期3:1-2 节 铜盘A110\n05-17 星期5:3-4节 铜盘A110\n',
      rawAdjust: '',
    },
    {
      name: '高级语言程序设计',
      teacher: '孙岚',
      scheduleRules: [
        {
          location: '铜盘A312',
          startClass: 7,
          endClass: 8,
          startWeek: 7,
          endWeek: 14,
          weekday: 3,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '铜盘A407',
          startClass: 5,
          endClass: 6,
          startWeek: 7,
          endWeek: 14,
          weekday: 5,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240101000008008',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=01000008',
      rawScheduleRules:
        '07-14 星期3:7-8节 铜盘A312\n07-14 星期5:5-6节 铜盘A407\n',
      rawAdjust: '',
    },
    {
      name: '计算机学科导论',
      teacher: '苏雅茹',
      scheduleRules: [
        {
          location: '铜盘B109',
          startClass: 5,
          endClass: 6,
          startWeek: 5,
          endWeek: 11,
          weekday: 1,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '铜盘A409',
          startClass: 3,
          endClass: 4,
          startWeek: 5,
          endWeek: 11,
          weekday: 4,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240101000099006',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=01000099',
      rawScheduleRules:
        '05-11 星期1:5-6节 铜盘B109\n05-11 星期4:3-4节 铜盘A409\n',
      rawAdjust: '',
    },
    {
      name: '认知实习',
      teacher: '苏雅茹',
      scheduleRules: [
        {
          location: '铜盘A205',
          startClass: 5,
          endClass: 8,
          startWeek: 12,
          endWeek: 17,
          weekday: 6,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240101000052006',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=01000052',
      rawScheduleRules: '12-17 星期6:5-8节 铜盘A205\n',
      rawAdjust: '',
    },
    {
      name: '高级语言程序设计实践111111111111111111111111111111111111111111111111111111',
      teacher: '孙岚',
      scheduleRules: [
        {
          location: '铜盘A205',
          startClass: 3,
          endClass: 4,
          startWeek: 8,
          endWeek: 16,
          weekday: 3,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '铜盘A508',
          startClass: 7,
          endClass: 8,
          startWeek: 8,
          endWeek: 16,
          weekday: 5,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240101000100003',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=01000100',
      rawScheduleRules:
        '08-16 星期3:3-4节 铜盘A205\n08-16 星期5:7-8节 铜 盘A508\n',
      rawAdjust: '',
    },
    {
      name: '军事技能',
      teacher: '张幼松',
      scheduleRules: [
        {
          location: '',
          startClass: 1,
          endClass: 8,
          startWeek: 3,
          endWeek: 4,
          weekday: 1,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '',
          startClass: 1,
          endClass: 8,
          startWeek: 3,
          endWeek: 4,
          weekday: 2,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '',
          startClass: 1,
          endClass: 8,
          startWeek: 3,
          endWeek: 4,
          weekday: 3,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '',
          startClass: 1,
          endClass: 8,
          startWeek: 3,
          endWeek: 4,
          weekday: 4,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '',
          startClass: 1,
          endClass: 8,
          startWeek: 3,
          endWeek: 4,
          weekday: 5,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '',
          startClass: 1,
          endClass: 8,
          startWeek: 3,
          endWeek: 4,
          weekday: 6,
          single: true,
          double: true,
          adjust: false,
        },
        {
          location: '',
          startClass: 1,
          endClass: 8,
          startWeek: 3,
          endWeek: 4,
          weekday: 7,
          single: true,
          double: true,
          adjust: false,
        },
      ],
      remark: '',
      lessonplan:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/skjh/TeachingPlan_view.aspx?kkhm=20240106700003178',
      syllabus:
        'https://jwcjwxt2.fzu.edu.cn:81/pyfa/jxdg/TeachingProgram_view.aspx?kcdm=06700003',
      rawScheduleRules: '03周  星期1  -  04周  星期7\n',
      rawAdjust: '',
    },
  ],
};
