name: Publish Alpha

on:
  workflow_call:

jobs:
  alpha:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: outputs
          path: ${{ github.workspace }}/outputs/

      - name: Extract Version Info
        id: version-info
        shell: bash
        run: |
          APP_VERSION_CODE=$(cat $GITHUB_WORKSPACE/outputs/version-code)
          APP_VERSION_NAME=$(cat $GITHUB_WORKSPACE/outputs/version-name)
          {
            echo "CHANGELOG<<BSEOF"
            cat $GITHUB_WORKSPACE/outputs/changelog
            echo "BSEOF"
          } >> "$GITHUB_OUTPUT"
          APK_FILENAME="FzuHelper_${APP_VERSION_NAME}(${APP_VERSION_CODE}).apk"
          echo "apk_filename=$APK_FILENAME" >> "$GITHUB_OUTPUT"
          mv $GITHUB_WORKSPACE/outputs/apk/release/app-arm64-v8a-release.apk $APK_FILENAME

      - name: Delete alpha using GitHub CLI
        run: |
          gh release delete alpha --yes >/dev/null 2>&1 || echo "No alpha release exists."
          gh api -X DELETE repos/${GITHUB_REPOSITORY}/git/refs/tags/alpha >/dev/null 2>&1 || echo "No alpha tag exists."
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create GitHub Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: alpha
          name: 'Alpha'
          body: |
            ${{ steps.version-info.outputs.CHANGELOG }}

            此版本为新架构测试版，请提前加入内测群 1020036141 了解详情
          prerelease: true
          files: |
            ${{ steps.version-info.outputs.apk_filename }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
