name: Publish Alpha

on:
  workflow_call:

jobs:
  alpha:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: outputs
          path: ${{ github.workspace }}/outputs/

      - name: Extract Version Info
        id: version-info
        shell: bash
        run: |
          echo "APP_VERSION_CODE=$(cat $GITHUB_WORKSPACE/outputs/version-code)" >> "$GITHUB_OUTPUT"
          echo "APP_VERSION_NAME=$(cat $GITHUB_WORKSPACE/outputs/version-name)" >> "$GITHUB_OUTPUT"
          {
            echo "CHANGELOG<<BSEOF"
            cat $GITHUB_WORKSPACE/outputs/changelog
            echo "BSEOF"
          } >> "$GITHUB_OUTPUT"
          echo "APK_FILENAME=FzuHelper_${APP_VERSION_NAME}(${APP_VERSION_CODE}).apk" >> "$GITHUB_OUTPUT"
          mv $GITHUB_WORKSPACE/outputs/apk/release/app-arm64-v8a-release.apk $APK_FILENAME

      - name: Delete alpha using GitHub CLI
        run: |
          if gh release view alpha; then
            gh release delete alpha --yes
          else
            echo "No alpha release exists."
          fi
          if gh tag view alpha; then
            gh tag delete alpha --yes
          else
            echo "No alpha tag exists."
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create GitHub Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: alpha
          name: 'Alpha'
          body: |
            ${{ steps.version-info.outputs.CHANGELOG }}

            此版本为新架构测试版，请提前加入内测群 1020036141 了解详情
          prerelease: true
          files: |
            ${{ steps.version-info.outputs.APK_FILENAME }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
