name: Build IPA

on:
  workflow_call:

jobs:
  build-ipa:
    runs-on: macos-26
    timeout-minutes: 60
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Restore Cache
        uses: actions/cache@v5
        with:
          path: |
            ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Checkout EAS CLI
        run: |
          git clone --branch feat/submit-by-local-machine --depth 1 https://github.com/west2-online/eas-cli.git

      - name: Cache EAS CLI Dependencies
        uses: actions/cache@v5
        with:
          path: eas-cli/node_modules
          key: ${{ runner.os }}-eas-cli-${{ hashFiles('eas-cli/yarn.lock') }}

      - name: Build EAS CLI
        run: |
          cd eas-cli
          corepack yarn install --frozen-lockfile
          corepack yarn build
        env:
          GH_TOKEN: ${{ github.token }}
      
      # EAS 本地构建会开很多奇怪的容器，这个环境变量保证 commit 正常计数
      - name: Get commit count
        id: commit_count
        run: |
          COUNT=$(git rev-list --count HEAD)
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
          echo "Commit count: $COUNT"  

      - name: EAS Build iOS
        run: |
          ./eas-cli/packages/eas-cli/bin/run build --platform ios --profile production --non-interactive --local --output=./build/fzuhelper.ipa
        env:
          EAS_SKIP_AUTO_FINGERPRINT: 1
          GIT_COMMIT_COUNT: ${{ steps.commit_count.outputs.count }}

      - name: Generate Changelog
        id: changelog
        run: |
          GIT_LOG=$(git log -n 3 --pretty=format:"%s" | awk '{print NR ". " $0}') || { echo "Failed to get git log"; exit 1; }
          {
            echo "CHANGELOG<<BSEOF"
            echo -e "同步自 GitHub 最近三条提交记录:\n$GIT_LOG"
            echo "BSEOF"
          } >> "$GITHUB_OUTPUT"

      - name: EAS Submit iOS
        run: |
          ./eas-cli/packages/eas-cli/bin/run submit --platform ios --profile production --non-interactive --local --path=./build/fzuhelper.ipa --what-to-test="${{ steps.changelog.outputs.CHANGELOG }}" \
          --fastlane-args="--distribute_external --reject_build_waiting_for_review"
