name: Publish Release

on:
  workflow_call:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download APK
        id: apk
        shell: bash
        run: |
          mkdir -p "$GITHUB_WORKSPACE/outputs/apk/release"
          gh release download alpha --pattern "FzuHelper_*.apk" --dir "$GITHUB_WORKSPACE/outputs/apk/release"

          APK_PATH=$(ls "$GITHUB_WORKSPACE"/outputs/apk/release/FzuHelper_*.apk | head -n 1)
          if [[ -z "$APK_PATH" ]]; then
              echo "Error: APK file not found in the release assets."
              exit 1
          fi

          echo "APK_PATH=$APK_PATH" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Generate Release Info
        id: info
        run: |
          CURRENT_VERSION=${GITHUB_REF_NAME}
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT

          echo "DATE_TIME<<EOF" >> $GITHUB_OUTPUT
          echo "### $(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.info.outputs.CURRENT_VERSION }}
          generate_release_notes: true # 自动生成发布说明
          body: ${{ steps.info.outputs.DATE_TIME }}
          make_latest: true
          files: |
            ${{ steps.apk.outputs.APK_PATH }}
