name: Auto Bump Version

on:
  workflow_call:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Extract Current Tag
        id: tag
        run: |
          CURRENT_TAG=${GITHUB_REF_NAME}
          echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_OUTPUT

      - name: Calculate Next Version
        id: version
        run: |
          IFS='.' read -r major minor patch <<< "${{ steps.tag.outputs.CURRENT_TAG }}"

          if [ "$patch" -lt 9 ]; then
            patch=$((patch+1))
          else
            patch=0
            if [ "$minor" -lt 9 ]; then
              minor=$((minor+1))
            else
              minor=0
              major=$((major+1))
            fi
          fi

          NEXT_VERSION="$major.$minor.$patch"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Bump Version
        run: |
          jq '.version = "${{ steps.version.outputs.NEXT_VERSION }}"' package.json > package.tmp && mv package.tmp package.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ github.token }}
          title: 'chore: bump version to ${{ steps.version.outputs.NEXT_VERSION }}'
          body: 'Auto bump version to ${{ steps.version.outputs.NEXT_VERSION }} (detected tag ${{ steps.tag.outputs.CURRENT_TAG }})'
          base: master
          branch: bump-version-${{ steps.version.outputs.NEXT_VERSION }}
          commit-message: 'chore: bump version to ${{ steps.version.outputs.NEXT_VERSION }}'
          sign-commits: true
